version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    reviewers:
      - lortza
    labels:
      - dependency-update
    ignore:
      - dependency-name: listen
        versions:
          - 3.4.1
          - 3.5.0
      - dependency-name: rails
        versions:
          - 6.1.1
          - 6.1.2
          - 6.1.2.1
          - 6.1.3
          - 6.1.3.1
      - dependency-name: nokogiri
        versions:
          - 1.11.1
          - 1.11.2
      - dependency-name: rspec-rails
        versions:
          - 4.0.2
          - 4.1.0
          - 4.1.1
          - 5.0.0
      - dependency-name: webdrivers
        versions:
          - 4.5.0
          - 4.6.0
      - dependency-name: bullet
        versions:
          - 6.1.3
          - 6.1.4
      - dependency-name: puma
        versions:
          - 5.2.0
          - 5.2.1
      - dependency-name: binding_of_caller
        versions:
          - 1.0.0
