require:
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true
AllCops:
  DefaultFormatter: progress
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'
    # - '**/*.erb'

Layout/LineLength:
  Max: 120
  Exclude:
  - !ruby/regexp /.*_spec\.rb$/

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
    - 'lib/tasks/*'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
