# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pain_log_quick_form_values', type: :request do
  # PainLogQuickFormValue. As you add validations to PainLogQuickFormValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip('Add a hash of attributes valid for your model')
  }

  let(:invalid_attributes) {
    skip('Add a hash of attributes invalid for your model')
  }

  describe 'GET /index' do
    it 'renders a successful response' do
      PainLogQuickFormValue.create! valid_attributes
      get pain_log_quick_form_values_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
      get pain_log_quick_form_value_url(pain_log_quick_form_value)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pain_log_quick_form_value_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
      get edit_pain_log_quick_form_value_url(pain_log_quick_form_value)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PainLogQuickFormValue' do
        expect {
          post pain_log_quick_form_values_url, params: { pain_log_quick_form_value: valid_attributes }
        }.to change(PainLogQuickFormValue, :count).by(1)
      end

      it 'redirects to the created pain_log_quick_form_value' do
        post pain_log_quick_form_values_url, params: { pain_log_quick_form_value: valid_attributes }
        expect(response).to redirect_to(pain_log_quick_form_value_url(PainLogQuickFormValue.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PainLogQuickFormValue' do
        expect {
          post pain_log_quick_form_values_url, params: { pain_log_quick_form_value: invalid_attributes }
        }.to change(PainLogQuickFormValue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pain_log_quick_form_values_url, params: { pain_log_quick_form_value: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) {
        skip('Add a hash of attributes valid for your model')
      }

      it 'updates the requested pain_log_quick_form_value' do
        pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
        patch pain_log_quick_form_value_url(pain_log_quick_form_value), params: { pain_log_quick_form_value: new_attributes }
        pain_log_quick_form_value.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pain_log_quick_form_value' do
        pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
        patch pain_log_quick_form_value_url(pain_log_quick_form_value), params: { pain_log_quick_form_value: new_attributes }
        pain_log_quick_form_value.reload
        expect(response).to redirect_to(pain_log_quick_form_value_url(pain_log_quick_form_value))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
        patch pain_log_quick_form_value_url(pain_log_quick_form_value), params: { pain_log_quick_form_value: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pain_log_quick_form_value' do
      pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
      expect {
        delete pain_log_quick_form_value_url(pain_log_quick_form_value)
      }.to change(PainLogQuickFormValue, :count).by(-1)
    end

    it 'redirects to the pain_log_quick_form_values list' do
      pain_log_quick_form_value = PainLogQuickFormValue.create! valid_attributes
      delete pain_log_quick_form_value_url(pain_log_quick_form_value)
      expect(response).to redirect_to(pain_log_quick_form_values_url)
    end
  end
end
